Better error checking and more granular use of sudo

diff --git a/src/vmm_mad/remotes/kvm/snapshot_create b/src/vmm_mad/remotes/kvm/snapshot_create
--- a/src/vmm_mad/remotes/kvm/snapshot_create
+++ b/src/vmm_mad/remotes/kvm/snapshot_create
@@ -39,7 +39,9 @@ function generateSnapshotCommands() {
 	xml="$(virsh --connect $LIBVIRT_URI dumpxml $DOMAIN 2>/dev/null)"
 
 	# Process every disk from the XML
-	for idx in {1..128}; do
+	idx='0'
+	while true; do
+		idx=$[$idx + 1]
 		(
 			IFS='' read -r -d '' type
 			IFS='' read -r -d '' device
@@ -88,7 +90,7 @@ function generateSnapshotCommands() {
 							exit -1
 							;;
 						file)
-							echo "qemu-img snapshot -c ${internalSnapshotName} $(set | awk -v var="sourceFile" '($0 ~ "^" var "="){ gsub("^" var "=", ""); print }')"
+							echo "sudo qemu-img snapshot -c ${internalSnapshotName} $(set | awk -v var="sourceFile" '($0 ~ "^" var "="){ gsub("^" var "=", ""); print }')"
 							;;
 						*)
 							error_message "Could not create snapshot $NAME for domain $DOMAIN: Unsupported libvirt disk type $type found"
@@ -133,15 +135,33 @@ case "${data}" in
 		commandsToRun="$(generateSnapshotCommands "${internalSnapshotName}")" || ( error_message "Could not create snapshot $NAME for domain $DOMAIN."; exit 1 ) || exit -1
 		commandsToRunCount="$(echo "${commandsToRun}" | wc -l | awk '{ print $1 }')"
 
+		# If we came up with nothing to do, fail
+		if [ "${commandsToRunCount}" = '0' ]; then
+			error_message "Could not create snapshot $NAME for domain $DOMAIN: No way to take a snapshot of any disks"
+			exit -1
+		fi
+
 		## Run the commands, pausing the VM if needed
 		if [ "${commandsToRunCount}" -gt '1' ]; then
 			virsh --connect $LIBVIRT_URI qemu-monitor-command --domain $DOMAIN --hmp --cmd stop >/dev/null
 		fi
 
-		echo "${commandsToRun}" | sudo sh - >&2
+		failed='0'
+		results="$(
+			(
+				echo "set -e"
+				echo "${commandsToRun}"
+			) | sh - 2>&1
+		)" || failed='1'
 
 		if [ "${commandsToRunCount}" -gt '1' ]; then
 			virsh --connect $LIBVIRT_URI qemu-monitor-command --domain $DOMAIN --hmp --cmd cont >/dev/null
+		fi
+
+		if [ "${failed}" = '1' ]; then
+			error_message "Could not create snapshot $NAME for domain $DOMAIN: $results"
+
+			exit -1
 		fi
 
 		echo "${internalSnapshotName}"
